package pqt.dss.rrf.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 13 11:27:07 PKT 2016
// ---------------------------------------------------------------------
public interface DssReinstatementRequestFormView extends ViewObject {
    void setNVC_WfDocumentId(oracle.jbo.domain.Number value);

    void rrfSearchUser();
}

